create or replace PACKAGE        CSDATRM
IS

	TYPE CSDATRM_TYPE IS RECORD
	(
		TF_CUSTOM_SERIAL_NO		CSDATRM.TF_CUSTOM_SERIAL_NO%TYPE,	--收文編號
		TF_FLAG		CSDATRM.TF_FLAG%TYPE,	--特殊註記(徹案)
		BAN		CSDATRM.BAN%TYPE,	--統一編號
		CCC_CODE		CSDATRM.CCC_CODE%TYPE,	--商品標準分類號列
		TF_ISSUE_DATE		CSDATRM.TF_ISSUE_DATE%TYPE,	--發文日期
		TF_ISSUE_DOCU_NO		CSDATRM.TF_ISSUE_DOCU_NO%TYPE,	--發文文號
		TF_ENGLISH_COMMODITY		CSDATRM.TF_ENGLISH_COMMODITY%TYPE,	--貨品名稱型號規格
		TF_M_B_NATION		CSDATRM.TF_M_B_NATION%TYPE,	--製造廠商廠牌生產國別
		TF_FACTOR_MATERIAL		CSDATRM.TF_FACTOR_MATERIAL%TYPE,	--材質成分
		TF_REPRODUCE_SUMMARY		CSDATRM.TF_REPRODUCE_SUMMARY%TYPE,	--加工製程概述
		TF_FUNCTION		CSDATRM.TF_FUNCTION%TYPE,	--用途
		TF_PACK_WAY		CSDATRM.TF_PACK_WAY%TYPE,	--包裝方式
		TF_OTHER_EXPLAIN		CSDATRM.TF_OTHER_EXPLAIN%TYPE,	--其他說明
		TF_HS_E_REASON		CSDATRM.TF_HS_E_REASON%TYPE,	--稅則分類理由
		TF_REMARK		CSDATRM.TF_REMARK%TYPE,	--備註
		TF_RECEIVE_DATE		CSDATRM.TF_RECEIVE_DATE%TYPE,	--受理日期
		TF_PERSON		CSDATRM.TF_PERSON%TYPE,	--承辦人代碼
		TF_HS_E_REASON_0		CSDATRM.TF_HS_E_REASON_0%TYPE,	--分類理由_總局
		TF_HS_E_REASON_A		CSDATRM.TF_HS_E_REASON_A%TYPE,	--分類理由_基隆關
		TF_HS_E_REASON_B		CSDATRM.TF_HS_E_REASON_B%TYPE,	--分類理由_高雄關
		TF_HS_E_REASON_C		CSDATRM.TF_HS_E_REASON_C%TYPE,	--分類理由_台北關
		TF_HS_E_REASON_D		CSDATRM.TF_HS_E_REASON_D%TYPE,	--分類理由_台中關
		TF_0DT		CSDATRM.TF_0DT%TYPE,	--分類理由異動日期_總局
		TF_ADT		CSDATRM.TF_ADT%TYPE,	--分類理由異動日期_基隆關
		TF_BDT		CSDATRM.TF_BDT%TYPE,	--分類理由異動日期_高雄關
		TF_CDT		CSDATRM.TF_CDT%TYPE,	--分類理由異動日期_台北關
		TF_DDT		CSDATRM.TF_DDT%TYPE,	--分類理由異動日期_台中關
		TF_0ID		CSDATRM.TF_0ID%TYPE,	--分類理由職員編號_總局
		TF_AID		CSDATRM.TF_AID%TYPE,	--分類理由職員編號_基隆關
		TF_BID		CSDATRM.TF_BID%TYPE,	--分類理由職員編號_高雄關
		TF_CID		CSDATRM.TF_CID%TYPE,	--分類理由職員編號_台北關
		TF_DID		CSDATRM.TF_DID%TYPE,	--分類理由職員編號_台中關
		TF_AIMPORT		CSDATRM.TF_AIMPORT%TYPE,	--進口紀錄_基隆關
		TF_BIMPORT		CSDATRM.TF_BIMPORT%TYPE,	--進口紀錄_高雄關
		TF_CIMPORT		CSDATRM.TF_CIMPORT%TYPE,	--進口紀錄_台北關
		TF_DIMPORT		CSDATRM.TF_DIMPORT%TYPE,	--進口紀錄_台中關
		BC_USER_0		CSDATRM.BC_USER_0%TYPE,	--承辦人員_總局
		BC_USER_A		CSDATRM.BC_USER_A%TYPE,	--承辦人員_基隆
		BC_USER_B		CSDATRM.BC_USER_B%TYPE,	--承辦人員_高雄
		BC_USER_C		CSDATRM.BC_USER_C%TYPE,	--承辦人員_台北
		BC_USER_D		CSDATRM.BC_USER_D%TYPE,	--承辦人員_台中
		TF_SENDMARK		CSDATRM.TF_SENDMARK%TYPE,	--傳送註記
		TF_SEND_DATE		CSDATRM.TF_SEND_DATE%TYPE,	--傳送註記日期
		TF_STATUS		CSDATRM.TF_STATUS%TYPE,	--案件處理流程代碼
		UP_PERSON		CSDATRM.UP_PERSON%TYPE,	--異動人員
		UP_DATE		CSDATRM.UP_DATE%TYPE,	--異動時間
		TF_REASON_MARK_0		CSDATRM.TF_REASON_MARK_0%TYPE,	--分類理由完成註記_總局
		TF_REASON_MARK_A		CSDATRM.TF_REASON_MARK_A%TYPE,	--分類理由完成註記_基隆關
		TF_REASON_MARK_B		CSDATRM.TF_REASON_MARK_B%TYPE,	--分類理由完成註記_高雄關
		TF_REASON_MARK_C		CSDATRM.TF_REASON_MARK_C%TYPE,	--分類理由完成註記_台北關
		TF_REASON_MARK_D		CSDATRM.TF_REASON_MARK_D%TYPE,	--分類理由完成註記_台中關
		TF_RENEW_DATE		CSDATRM.TF_RENEW_DATE%TYPE,	--補件日期
		TF_HS_E_MARK		CSDATRM.TF_HS_E_MARK%TYPE,	--稅則分類理由_完成註記
		TF_APP_NAME		CSDATRM.TF_APP_NAME%TYPE,	--申請廠商名稱
		TF_APP_TEL		CSDATRM.TF_APP_TEL%TYPE,	--申請廠商電話
		TF_APP_ADDRESS		CSDATRM.TF_APP_ADDRESS%TYPE	--申請廠商地址
	);

END CSDATRM;
