SELECT
	TF_CUSTOM_SERIAL_NO,		--收文編號
	TF_FLAG,		--特殊註記(徹案)
	BAN,		--統一編號
	CCC_CODE,		--商品標準分類號列
	TF_ISSUE_DATE,		--發文日期
	TF_ISSUE_DOCU_NO,		--發文文號
	TF_ENGLISH_COMMODITY,		--貨品名稱型號規格
	TF_M_B_NATION,		--製造廠商廠牌生產國別
	TF_FACTOR_MATERIAL,		--材質成分
	TF_REPRODUCE_SUMMARY,		--加工製程概述
	TF_FUNCTION,		--用途
	TF_PACK_WAY,		--包裝方式
	TF_OTHER_EXPLAIN,		--其他說明
	TF_HS_E_REASON,		--稅則分類理由
	TF_REMARK,		--備註
	TF_RECEIVE_DATE,		--受理日期
	TF_PERSON,		--承辦人代碼
	TF_HS_E_REASON_0,		--分類理由_總局
	TF_HS_E_REASON_A,		--分類理由_基隆關
	TF_HS_E_REASON_B,		--分類理由_高雄關
	TF_HS_E_REASON_C,		--分類理由_台北關
	TF_HS_E_REASON_D,		--分類理由_台中關
	TF_0DT,		--分類理由異動日期_總局
	TF_ADT,		--分類理由異動日期_基隆關
	TF_BDT,		--分類理由異動日期_高雄關
	TF_CDT,		--分類理由異動日期_台北關
	TF_DDT,		--分類理由異動日期_台中關
	TF_0ID,		--分類理由職員編號_總局
	TF_AID,		--分類理由職員編號_基隆關
	TF_BID,		--分類理由職員編號_高雄關
	TF_CID,		--分類理由職員編號_台北關
	TF_DID,		--分類理由職員編號_台中關
	TF_AIMPORT,		--進口紀錄_基隆關
	TF_BIMPORT,		--進口紀錄_高雄關
	TF_CIMPORT,		--進口紀錄_台北關
	TF_DIMPORT,		--進口紀錄_台中關
	BC_USER_0,		--承辦人員_總局
	BC_USER_A,		--承辦人員_基隆
	BC_USER_B,		--承辦人員_高雄
	BC_USER_C,		--承辦人員_台北
	BC_USER_D,		--承辦人員_台中
	TF_SENDMARK,		--傳送註記
	TF_SEND_DATE,		--傳送註記日期
	TF_STATUS,		--案件處理流程代碼
	UP_PERSON,		--異動人員
	UP_DATE,		--異動時間
	TF_REASON_MARK_0,		--分類理由完成註記_總局
	TF_REASON_MARK_A,		--分類理由完成註記_基隆關
	TF_REASON_MARK_B,		--分類理由完成註記_高雄關
	TF_REASON_MARK_C,		--分類理由完成註記_台北關
	TF_REASON_MARK_D,		--分類理由完成註記_台中關
	TF_RENEW_DATE,		--補件日期
	TF_HS_E_MARK,		--稅則分類理由_完成註記
	TF_APP_NAME,		--申請廠商名稱
	TF_APP_TEL,		--申請廠商電話
	TF_APP_ADDRESS		--申請廠商地址
FROM CSDATRM
WHERE
	TF_CUSTOM_SERIAL_NO = CSDATRM.TF_CUSTOM_SERIAL_NO  AND  
	TF_FLAG = CSDATRM.TF_FLAG  AND  
	BAN = CSDATRM.BAN  AND  
	CCC_CODE = CSDATRM.CCC_CODE  AND  
	TF_ISSUE_DATE = CSDATRM.TF_ISSUE_DATE  AND  
	TF_ISSUE_DOCU_NO = CSDATRM.TF_ISSUE_DOCU_NO  AND  
	TF_ENGLISH_COMMODITY = CSDATRM.TF_ENGLISH_COMMODITY  AND  
	TF_M_B_NATION = CSDATRM.TF_M_B_NATION  AND  
	TF_FACTOR_MATERIAL = CSDATRM.TF_FACTOR_MATERIAL  AND  
	TF_REPRODUCE_SUMMARY = CSDATRM.TF_REPRODUCE_SUMMARY  AND  
	TF_FUNCTION = CSDATRM.TF_FUNCTION  AND  
	TF_PACK_WAY = CSDATRM.TF_PACK_WAY  AND  
	TF_OTHER_EXPLAIN = CSDATRM.TF_OTHER_EXPLAIN  AND  
	TF_HS_E_REASON = CSDATRM.TF_HS_E_REASON  AND  
	TF_REMARK = CSDATRM.TF_REMARK  AND  
	TF_RECEIVE_DATE = CSDATRM.TF_RECEIVE_DATE  AND  
	TF_PERSON = CSDATRM.TF_PERSON  AND  
	TF_HS_E_REASON_0 = CSDATRM.TF_HS_E_REASON_0  AND  
	TF_HS_E_REASON_A = CSDATRM.TF_HS_E_REASON_A  AND  
	TF_HS_E_REASON_B = CSDATRM.TF_HS_E_REASON_B  AND  
	TF_HS_E_REASON_C = CSDATRM.TF_HS_E_REASON_C  AND  
	TF_HS_E_REASON_D = CSDATRM.TF_HS_E_REASON_D  AND  
	TF_0DT = CSDATRM.TF_0DT  AND  
	TF_ADT = CSDATRM.TF_ADT  AND  
	TF_BDT = CSDATRM.TF_BDT  AND  
	TF_CDT = CSDATRM.TF_CDT  AND  
	TF_DDT = CSDATRM.TF_DDT  AND  
	TF_0ID = CSDATRM.TF_0ID  AND  
	TF_AID = CSDATRM.TF_AID  AND  
	TF_BID = CSDATRM.TF_BID  AND  
	TF_CID = CSDATRM.TF_CID  AND  
	TF_DID = CSDATRM.TF_DID  AND  
	TF_AIMPORT = CSDATRM.TF_AIMPORT  AND  
	TF_BIMPORT = CSDATRM.TF_BIMPORT  AND  
	TF_CIMPORT = CSDATRM.TF_CIMPORT  AND  
	TF_DIMPORT = CSDATRM.TF_DIMPORT  AND  
	BC_USER_0 = CSDATRM.BC_USER_0  AND  
	BC_USER_A = CSDATRM.BC_USER_A  AND  
	BC_USER_B = CSDATRM.BC_USER_B  AND  
	BC_USER_C = CSDATRM.BC_USER_C  AND  
	BC_USER_D = CSDATRM.BC_USER_D  AND  
	TF_SENDMARK = CSDATRM.TF_SENDMARK  AND  
	TF_SEND_DATE = CSDATRM.TF_SEND_DATE  AND  
	TF_STATUS = CSDATRM.TF_STATUS  AND  
	UP_PERSON = CSDATRM.UP_PERSON  AND  
	UP_DATE = CSDATRM.UP_DATE  AND  
	TF_REASON_MARK_0 = CSDATRM.TF_REASON_MARK_0  AND  
	TF_REASON_MARK_A = CSDATRM.TF_REASON_MARK_A  AND  
	TF_REASON_MARK_B = CSDATRM.TF_REASON_MARK_B  AND  
	TF_REASON_MARK_C = CSDATRM.TF_REASON_MARK_C  AND  
	TF_REASON_MARK_D = CSDATRM.TF_REASON_MARK_D  AND  
	TF_RENEW_DATE = CSDATRM.TF_RENEW_DATE  AND  
	TF_HS_E_MARK = CSDATRM.TF_HS_E_MARK  AND  
	TF_APP_NAME = CSDATRM.TF_APP_NAME  AND  
	TF_APP_TEL = CSDATRM.TF_APP_TEL  AND  
	TF_APP_ADDRESS = CSDATRM.TF_APP_ADDRESS;
