SELECT
	TRANS_TYPE_CD,		--訊息功能代碼
	MAWB,		--託運單主號
	HAWB,		--託運單分號
	DECL_NO,		--報單號碼
	DECL_CUST_CD,		--報單關別
	SEQ_NO,		--序號
	DECL_TYPE,		--報單類別
	BROKER_BOX_NO,		--業者箱號
	BROKER_SUB_BOX_NO,		--箱號附碼
	BROKER_EMP,		--專責報關人員代號
	STOR_WARE_CD,		--卸存地點代碼
	EXPORTER_BAN,		--輸出人統一編號
	EXPORTER_ENAME,		--輸出人英文名稱
	EXPORTER_CNAME,		--輸出人中文名稱
	EXPORTER_EADDR,		--輸出人英文地址
	EXPORTER_CADDR,		--輸出人中文地址
	EXPRESS_CARRIER_BAN,		--快遞業者統一編號
	EXPRESS_CARRIER_ENAME,		--快遞業者英文名稱
	EXPRESS_CARRIER_CNAME,		--快遞業者中文名稱
	ON_BOARD_COURIER_BAN,		--快遞專差統一編號
	ON_BOARD_COURIER_ENAME,		--快遞專差英文名稱
	ON_BOARD_COURIER_CNAME,		--快遞專差中文名稱
	CONSOLIDATED_BAG_NO,		--併袋號碼
	TOTAL_HAWB,		--併袋筆數
	DECL_DATE,		--報關日期
	VOYAGE_FLIGHT_NO,		--船舶航機班次
	SAL_BAN,		--貨物輸出人統一編號
	SAL_ENAME,		--貨物輸出人英文名稱
	SAL_CNAME,		--貨物輸出人中文名稱
	SAL_EADDR,		--貨物輸出人英文地址
	SAL_CADDR,		--貨物輸出人中文地址
	DEST_CD,		--目的地代碼
	TOT_PACK_QTY,		--總件數
	PACK_UNIT,		--件數單位
	TOT_GROSS_WEIGHT,		--總毛重
	TOT_TWD_FOB,		--總離岸價格(新台幣)
	PRO_TYPE,		--訊息功能代碼
	CLEAR_TYPE,		--通關方式
	EXAM_MARK,		--驗貨註記
	RLS_NOTE,		--放行註記
	REL_DATE,		--放行日期時間
	REL_PACK,		--放行件數
	EXAM_COUNTER,		--驗貨檯號
	SENDER_ID,		--傳送方代碼
	CONTROL_NUMBER,		--交換控制碼
	TRANS_ID,		--訊息處理編號
	DEAL_DATE,		--訊息處理時間
	RECEIVER_ID,		--接收方代碼
	RECV_FINISH_DATE		--收單完成時間
FROM EXZEZMM
WHERE
	TRANS_TYPE_CD = EXZEZMM.TRANS_TYPE_CD  AND  
	MAWB = EXZEZMM.MAWB  AND  
	HAWB = EXZEZMM.HAWB  AND  
	DECL_NO = EXZEZMM.DECL_NO  AND  
	DECL_CUST_CD = EXZEZMM.DECL_CUST_CD  AND  
	SEQ_NO = EXZEZMM.SEQ_NO  AND  
	DECL_TYPE = EXZEZMM.DECL_TYPE  AND  
	BROKER_BOX_NO = EXZEZMM.BROKER_BOX_NO  AND  
	BROKER_SUB_BOX_NO = EXZEZMM.BROKER_SUB_BOX_NO  AND  
	BROKER_EMP = EXZEZMM.BROKER_EMP  AND  
	STOR_WARE_CD = EXZEZMM.STOR_WARE_CD  AND  
	EXPORTER_BAN = EXZEZMM.EXPORTER_BAN  AND  
	EXPORTER_ENAME = EXZEZMM.EXPORTER_ENAME  AND  
	EXPORTER_CNAME = EXZEZMM.EXPORTER_CNAME  AND  
	EXPORTER_EADDR = EXZEZMM.EXPORTER_EADDR  AND  
	EXPORTER_CADDR = EXZEZMM.EXPORTER_CADDR  AND  
	EXPRESS_CARRIER_BAN = EXZEZMM.EXPRESS_CARRIER_BAN  AND  
	EXPRESS_CARRIER_ENAME = EXZEZMM.EXPRESS_CARRIER_ENAME  AND  
	EXPRESS_CARRIER_CNAME = EXZEZMM.EXPRESS_CARRIER_CNAME  AND  
	ON_BOARD_COURIER_BAN = EXZEZMM.ON_BOARD_COURIER_BAN  AND  
	ON_BOARD_COURIER_ENAME = EXZEZMM.ON_BOARD_COURIER_ENAME  AND  
	ON_BOARD_COURIER_CNAME = EXZEZMM.ON_BOARD_COURIER_CNAME  AND  
	CONSOLIDATED_BAG_NO = EXZEZMM.CONSOLIDATED_BAG_NO  AND  
	TOTAL_HAWB = EXZEZMM.TOTAL_HAWB  AND  
	DECL_DATE = EXZEZMM.DECL_DATE  AND  
	VOYAGE_FLIGHT_NO = EXZEZMM.VOYAGE_FLIGHT_NO  AND  
	SAL_BAN = EXZEZMM.SAL_BAN  AND  
	SAL_ENAME = EXZEZMM.SAL_ENAME  AND  
	SAL_CNAME = EXZEZMM.SAL_CNAME  AND  
	SAL_EADDR = EXZEZMM.SAL_EADDR  AND  
	SAL_CADDR = EXZEZMM.SAL_CADDR  AND  
	DEST_CD = EXZEZMM.DEST_CD  AND  
	TOT_PACK_QTY = EXZEZMM.TOT_PACK_QTY  AND  
	PACK_UNIT = EXZEZMM.PACK_UNIT  AND  
	TOT_GROSS_WEIGHT = EXZEZMM.TOT_GROSS_WEIGHT  AND  
	TOT_TWD_FOB = EXZEZMM.TOT_TWD_FOB  AND  
	PRO_TYPE = EXZEZMM.PRO_TYPE  AND  
	CLEAR_TYPE = EXZEZMM.CLEAR_TYPE  AND  
	EXAM_MARK = EXZEZMM.EXAM_MARK  AND  
	RLS_NOTE = EXZEZMM.RLS_NOTE  AND  
	REL_DATE = EXZEZMM.REL_DATE  AND  
	REL_PACK = EXZEZMM.REL_PACK  AND  
	EXAM_COUNTER = EXZEZMM.EXAM_COUNTER  AND  
	SENDER_ID = EXZEZMM.SENDER_ID  AND  
	CONTROL_NUMBER = EXZEZMM.CONTROL_NUMBER  AND  
	TRANS_ID = EXZEZMM.TRANS_ID  AND  
	DEAL_DATE = EXZEZMM.DEAL_DATE  AND  
	RECEIVER_ID = EXZEZMM.RECEIVER_ID  AND  
	RECV_FINISH_DATE = EXZEZMM.RECV_FINISH_DATE;
