create or replace PACKAGE        EXZEZDM
IS

	TYPE EXZEZDM_TYPE IS RECORD
	(
		MAWB		EXZEZDM.MAWB%TYPE,	--託運單主號
		HAWB		EXZEZDM.HAWB%TYPE,	--託運單分號
		ITEM_NO		EXZEZDM.ITEM_NO%TYPE,	--序號
		GOODS_DESC		EXZEZDM.GOODS_DESC%TYPE,	--貨物名稱
		BRAND		EXZEZDM.BRAND%TYPE,	--牌名(商標)
		MODEL		EXZEZDM.MODEL%TYPE,	--型號
		SPEC		EXZEZDM.SPEC%TYPE,	--成分及規格
		CCC_CODE		EXZEZDM.CCC_CODE%TYPE,	--貨品分類號列
		QTY		EXZEZDM.QTY%TYPE,	--數量
		QTY_UNIT		EXZEZDM.QTY_UNIT%TYPE,	--數量單位
		NET_WEIGHT		EXZEZDM.NET_WEIGHT%TYPE,	--淨重
		TWD_FOB		EXZEZDM.TWD_FOB%TYPE,	--離岸價格(新台幣)
		ST_MODE		EXZEZDM.ST_MODE%TYPE	--統計方式代碼
	);

END EXZEZDM;

