SELECT
	MAWB,		--託運單主號
	HAWB,		--託運單分號
	ITEM_NO,		--序號
	GOODS_DESC,		--貨物名稱
	BRAND,		--牌名(商標)
	MODEL,		--型號
	SPEC,		--成分及規格
	CCC_CODE,		--貨品分類號列
	QTY,		--數量
	QTY_UNIT,		--數量單位
	NET_WEIGHT,		--淨重
	TWD_FOB,		--離岸價格(新台幣)
	ST_MODE		--統計方式代碼
FROM EXZEZDM
WHERE
	MAWB = EXZEZDM.MAWB  AND  
	HAWB = EXZEZDM.HAWB  AND  
	ITEM_NO = EXZEZDM.ITEM_NO  AND  
	GOODS_DESC = EXZEZDM.GOODS_DESC  AND  
	BRAND = EXZEZDM.BRAND  AND  
	MODEL = EXZEZDM.MODEL  AND  
	SPEC = EXZEZDM.SPEC  AND  
	CCC_CODE = EXZEZDM.CCC_CODE  AND  
	QTY = EXZEZDM.QTY  AND  
	QTY_UNIT = EXZEZDM.QTY_UNIT  AND  
	NET_WEIGHT = EXZEZDM.NET_WEIGHT  AND  
	TWD_FOB = EXZEZDM.TWD_FOB  AND  
	ST_MODE = EXZEZDM.ST_MODE;
