create or replace PACKAGE        EXZEZMM
IS

	TYPE EXZEZMM_TYPE IS RECORD
	(
		TRANS_TYPE_CD		EXZEZMM.TRANS_TYPE_CD%TYPE,	--訊息功能代碼
		MAWB		EXZEZMM.MAWB%TYPE,	--託運單主號
		HAWB		EXZEZMM.HAWB%TYPE,	--託運單分號
		DECL_NO		EXZEZMM.DECL_NO%TYPE,	--報單號碼
		DECL_CUST_CD		EXZEZMM.DECL_CUST_CD%TYPE,	--報單關別
		SEQ_NO		EXZEZMM.SEQ_NO%TYPE,	--序號
		DECL_TYPE		EXZEZMM.DECL_TYPE%TYPE,	--報單類別
		BROKER_BOX_NO		EXZEZMM.BROKER_BOX_NO%TYPE,	--業者箱號
		BROKER_SUB_BOX_NO		EXZEZMM.BROKER_SUB_BOX_NO%TYPE,	--箱號附碼
		BROKER_EMP		EXZEZMM.BROKER_EMP%TYPE,	--專責報關人員代號
		STOR_WARE_CD		EXZEZMM.STOR_WARE_CD%TYPE,	--卸存地點代碼
		EXPORTER_BAN		EXZEZMM.EXPORTER_BAN%TYPE,	--輸出人統一編號
		EXPORTER_ENAME		EXZEZMM.EXPORTER_ENAME%TYPE,	--輸出人英文名稱
		EXPORTER_CNAME		EXZEZMM.EXPORTER_CNAME%TYPE,	--輸出人中文名稱
		EXPORTER_EADDR		EXZEZMM.EXPORTER_EADDR%TYPE,	--輸出人英文地址
		EXPORTER_CADDR		EXZEZMM.EXPORTER_CADDR%TYPE,	--輸出人中文地址
		EXPRESS_CARRIER_BAN		EXZEZMM.EXPRESS_CARRIER_BAN%TYPE,	--快遞業者統一編號
		EXPRESS_CARRIER_ENAME		EXZEZMM.EXPRESS_CARRIER_ENAME%TYPE,	--快遞業者英文名稱
		EXPRESS_CARRIER_CNAME		EXZEZMM.EXPRESS_CARRIER_CNAME%TYPE,	--快遞業者中文名稱
		ON_BOARD_COURIER_BAN		EXZEZMM.ON_BOARD_COURIER_BAN%TYPE,	--快遞專差統一編號
		ON_BOARD_COURIER_ENAME		EXZEZMM.ON_BOARD_COURIER_ENAME%TYPE,	--快遞專差英文名稱
		ON_BOARD_COURIER_CNAME		EXZEZMM.ON_BOARD_COURIER_CNAME%TYPE,	--快遞專差中文名稱
		CONSOLIDATED_BAG_NO		EXZEZMM.CONSOLIDATED_BAG_NO%TYPE,	--併袋號碼
		TOTAL_HAWB		EXZEZMM.TOTAL_HAWB%TYPE,	--併袋筆數
		DECL_DATE		EXZEZMM.DECL_DATE%TYPE,	--報關日期
		VOYAGE_FLIGHT_NO		EXZEZMM.VOYAGE_FLIGHT_NO%TYPE,	--船舶航機班次
		SAL_BAN		EXZEZMM.SAL_BAN%TYPE,	--貨物輸出人統一編號
		SAL_ENAME		EXZEZMM.SAL_ENAME%TYPE,	--貨物輸出人英文名稱
		SAL_CNAME		EXZEZMM.SAL_CNAME%TYPE,	--貨物輸出人中文名稱
		SAL_EADDR		EXZEZMM.SAL_EADDR%TYPE,	--貨物輸出人英文地址
		SAL_CADDR		EXZEZMM.SAL_CADDR%TYPE,	--貨物輸出人中文地址
		DEST_CD		EXZEZMM.DEST_CD%TYPE,	--目的地代碼
		TOT_PACK_QTY		EXZEZMM.TOT_PACK_QTY%TYPE,	--總件數
		PACK_UNIT		EXZEZMM.PACK_UNIT%TYPE,	--件數單位
		TOT_GROSS_WEIGHT		EXZEZMM.TOT_GROSS_WEIGHT%TYPE,	--總毛重
		TOT_TWD_FOB		EXZEZMM.TOT_TWD_FOB%TYPE,	--總離岸價格(新台幣)
		PRO_TYPE		EXZEZMM.PRO_TYPE%TYPE,	--訊息功能代碼
		CLEAR_TYPE		EXZEZMM.CLEAR_TYPE%TYPE,	--通關方式
		EXAM_MARK		EXZEZMM.EXAM_MARK%TYPE,	--驗貨註記
		RLS_NOTE		EXZEZMM.RLS_NOTE%TYPE,	--放行註記
		REL_DATE		EXZEZMM.REL_DATE%TYPE,	--放行日期時間
		REL_PACK		EXZEZMM.REL_PACK%TYPE,	--放行件數
		EXAM_COUNTER		EXZEZMM.EXAM_COUNTER%TYPE,	--驗貨檯號
		SENDER_ID		EXZEZMM.SENDER_ID%TYPE,	--傳送方代碼
		CONTROL_NUMBER		EXZEZMM.CONTROL_NUMBER%TYPE,	--交換控制碼
		TRANS_ID		EXZEZMM.TRANS_ID%TYPE,	--訊息處理編號
		DEAL_DATE		EXZEZMM.DEAL_DATE%TYPE,	--訊息處理時間
		RECEIVER_ID		EXZEZMM.RECEIVER_ID%TYPE,	--接收方代碼
		RECV_FINISH_DATE		EXZEZMM.RECV_FINISH_DATE%TYPE	--收單完成時間
	);

END EXZEZMM;

